/**
 * Source for the one-shot CLI setup runner (`nexpath-setup-runner.cjs`).
 *
 * We run the actual setup as a small Node script INSIDE the user's integrated
 * terminal rather than chaining shell commands, because:
 *   - shell operator support differs across OSes (Windows PowerShell 5.1 lacks
 *     `&&`/`||`), so a single chained command isn't portable;
 *   - a Node driver can sequence steps, inherit the terminal's TTY for each
 *     child (so the CLI's interactive clack prompts — yes/no, API key — work
 *     exactly as in a manual install), and write a completion sentinel the
 *     extension watches for, all cross-platform.
 *
 * The runner is generated from this pure function (so it is unit-testable) and
 * written to `~/.nexpath/` at setup time. It performs the SAME steps a user does
 * by hand: install the CLI's production deps reproducibly (`npm ci` against the
 * bundled lockfile — wipes node_modules + installs the exact built/tested tree,
 * so a half-written/corrupted prior install can never survive and caret ranges
 * can't drift; falls back to a clean `npm install` if the lockfile is missing or
 * out of sync), then register Cursor + Windsurf via a single interactive
 * `--for vscode` pass. Argv: stagedDir, sentinel, cliEntry.
 */
export function buildSetupRunnerSource(): string {
  return `'use strict';
// GENERATED by the Nexpath VS Code extension — do not edit. Runs the one-time
// nexpath CLI setup in the integrated terminal and writes a completion sentinel.
const { spawnSync } = require('node:child_process');
const { writeFileSync, rmSync } = require('node:fs');
const { join } = require('node:path');

const stagedDir = process.argv[2];
const sentinel  = process.argv[3];
const cliEntry  = process.argv[4];
const node      = process.execPath;
const isWin     = process.platform === 'win32';

function step(label, cmd, args, opts) {
  process.stdout.write('\\n\\u203a Nexpath setup — ' + label + '\\n');
  const r = spawnSync(cmd, args, Object.assign({ stdio: 'inherit', cwd: stagedDir }, opts || {}));
  if (r.error) { process.stdout.write(String(r.error.message) + '\\n'); return false; }
  return r.status === 0;
}

let failed = null;

// 1. Install the CLI's production dependencies for THIS machine's platform
//    (fetches the correct native prebuilds). npm is npm.cmd on Windows → shell.
//    Prefer 'npm ci': it wipes node_modules first and installs EXACTLY the
//    bundled lockfile, so the dist always gets the tree it was built/tested
//    against and a corrupted/partial prior install self-heals. If ci can't run
//    (lockfile missing or out of sync — ci is strict), clear node_modules so no
//    broken tree survives, then fall back to a plain 'npm install'.
const npmFlags = ['--omit=dev', '--no-audit', '--no-fund', '--loglevel=error'];
if (!step('installing dependencies (npm ci)', 'npm',
          ['ci'].concat(npmFlags), { shell: isWin })) {
  try { rmSync(join(stagedDir, 'node_modules'), { recursive: true, force: true }); } catch (e) {}
  if (!step('installing dependencies (npm install fallback)', 'npm',
            ['install'].concat(npmFlags), { shell: isWin })) {
    failed = 'npm install';
  }
}

// 2. Register Cursor + Windsurf for VS Code — INTERACTIVE. This extension's
//    platform IS VS Code, so it installs '--for vscode' (the user answers API
//    key, telemetry, the agent-register confirm, frequency, role — the full
//    flow, exactly like the CLI). No separate Claude Code / '--for cli' pass:
//    Claude is a CLI agent set up via the CLI, not this extension.
if (!failed && !step('registering Cursor + Windsurf (interactive)', node,
                     [cliEntry, 'install', '--for', 'vscode'])) {
  failed = 'install --for vscode';
}

try { writeFileSync(sentinel, failed ? 'FAIL:' + failed : 'OK'); } catch (e) {}

if (failed) {
  process.stdout.write('\\n\\u2717 Nexpath setup failed at: ' + failed +
    '. Re-run from the Command Palette: "Nexpath: Set up CLI".\\n');
  process.exitCode = 1;
} else {
  process.stdout.write('\\n\\u2713 Nexpath setup complete. You can close this terminal.\\n');
}
`;
}

/** Filenames the runner + sentinel are written under in ~/.nexpath. */
export const SETUP_RUNNER_FILENAME = 'nexpath-setup-runner.cjs';
export const SETUP_SENTINEL_FILENAME = '.setup-sentinel';
