#!/usr/bin/env bash
# run-s09-windsurf.sh — S09 — Pure Vibe Coder / TrendPulse / Extended Project
#
# Cross-OS (Linux / macOS / Windows-Git-Bash) Windsurf + Nexpath behaviour test.
# Capture = Cascade hook; delivery = nexpath extension (status bar → sidebar →
# inject). Keep _windsurf-test-lib.sh next to this file. Layer C byte-identical
# to sub-7, so the fire/silent pattern matches the CLI sim.
#
# Usage:  bash run-s09-windsurf.sh
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SCENARIO_ID="S09"
SCENARIO_TITLE="S09 — Pure Vibe Coder / TrendPulse / Extended Project"
SCENARIO_PERSONA="Aisha — 200K followers, zero coding knowledge, 340 prompts across 5 releases"
INIT_NAME="trendPulse-windsurf-test"
INIT_TYPE="Web App"
INIT_LANG="JavaScript"
INIT_DESC="Social media content scheduling and trend tracking app"
TOTAL_PROMPTS=340
EXPECTED_ADVISORIES=32

# shellcheck source=_windsurf-test-lib.sh
source "$SCRIPT_DIR/_windsurf-test-lib.sh"

windsurf_test_setup

# ─── S09 prompts (340) ─────────────────────────────────────────────────
run_prompt 1 "make me an app that shows me whats trending on twitter and instagram so i can post about it before everyone else" "NO" "" "" "silent (min gate)"
run_prompt 2 "i also want it to help me write captions using ai and schedule my posts automatically" "NO" "" "" "silent (min gate)"
run_prompt 3 "start with a dashboard that shows trending topics with how fast they are growing" "YES" "stage_transition" "1" "stage_transition (idea → impl skip)"
run_prompt 4 "add a way to connect my twitter account" "NO" "" "" "silent (post-cooldown)"
run_prompt 5 "connect my instagram too" "NO" "" "" "silent"
run_prompt 6 "add linkedin and tiktok connections" "NO" "" "" "silent"
run_prompt 7 "show trending topics from twitter on the dashboard" "NO" "" "" "silent"
run_prompt 8 "add reddit trends too" "NO" "" "" "silent"
run_prompt 9 "add google trends" "NO" "" "" "silent"
run_prompt 10 "show a score for each trend so i know which ones are biggest" "NO" "" "" "silent"
run_prompt 11 "add login so nobody else can see my dashboard" "NO" "" "" "silent"
run_prompt 12 "send me an alert when something starts trending in my topics" "NO" "" "" "silent"
run_prompt 13 "add a way to set which topics i want to track" "NO" "" "" "silent"
run_prompt 14 "show the trend alert as a notification in the app" "NO" "" "" "silent"
run_prompt 15 "also send the alert to my email" "NO" "" "" "silent"
run_prompt 16 "add a content calendar where i can see my scheduled posts" "NO" "" "" "silent"
run_prompt 17 "add a way to create a new post and pick which platform to post on" "NO" "" "" "silent"
run_prompt 18 "add the ai caption writer that gives me 3 options for each post" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 19 "the ai should know twitter is short and linkedin is longer" "NO" "" "" "silent (post-cooldown)"
run_prompt 20 "add hashtag suggestions when i write a post" "NO" "" "" "silent"
run_prompt 21 "add a way to pick a date and time to schedule the post" "NO" "" "" "silent"
run_prompt 22 "make the post automatically publish at the scheduled time" "NO" "" "" "silent"
run_prompt 23 "show if the post was published successfully or failed" "NO" "" "" "silent"
run_prompt 24 "add analytics that show how many likes and comments my posts got" "NO" "" "" "silent"
run_prompt 25 "show a chart of my engagement over time" "NO" "" "" "silent"
run_prompt 26 "add a way to post to multiple platforms at once" "NO" "" "" "silent"
run_prompt 27 "the multi platform post should adjust the text for each platform" "NO" "" "" "silent"
run_prompt 28 "add image upload for posts" "NO" "" "" "silent"
run_prompt 29 "add video upload too" "NO" "" "" "silent"
run_prompt 30 "the calendar should show different colors for each platform" "NO" "" "" "silent"
run_prompt 31 "add drag and drop to move posts to different times on the calendar" "NO" "" "" "silent"
run_prompt 32 "add a way to save posts as drafts" "NO" "" "" "silent"
run_prompt 33 "add a way to see which of my posts performed best this week" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 34 "show best time to post based on when my followers are most active" "NO" "" "" "silent (post-cooldown)"
run_prompt 35 "the trend dashboard looks plain make it look nice with charts and colors" "NO" "" "" "silent"
run_prompt 36 "add a dark mode" "NO" "" "" "silent"
run_prompt 37 "make it work on my phone" "NO" "" "" "silent"
run_prompt 38 "the trends should refresh automatically without me reloading the page" "NO" "" "" "silent"
run_prompt 39 "add a way to see old trends from last week" "NO" "" "" "silent"
run_prompt 40 "show which of my past posts were about trending topics" "NO" "" "" "silent"
run_prompt 41 "add a content library where i can save my best captions" "NO" "" "" "silent"
run_prompt 42 "add a way to reuse a saved caption for a new post" "NO" "" "" "silent"
run_prompt 43 "the instagram posting is not working fix it" "NO" "" "" "silent"
run_prompt 44 "the twitter connection keeps disconnecting fix it" "NO" "" "" "silent"
run_prompt 45 "add a way to see how many followers i gained this week" "NO" "" "" "silent"
run_prompt 46 "show follower growth as a chart" "NO" "" "" "silent"
run_prompt 47 "add a weekly summary that shows all my stats" "NO" "" "" "silent"
run_prompt 48 "send me the weekly summary by email every monday" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 49 "add a way to create post templates" "NO" "" "" "silent (post-cooldown)"
run_prompt 50 "templates should have placeholders like the topic name and date" "NO" "" "" "silent"
run_prompt 51 "add recurring posts that repeat every week" "NO" "" "" "silent"
run_prompt 52 "add a way to see competitor accounts and what they post" "NO" "" "" "silent"
run_prompt 53 "show how my engagement compares to competitors" "NO" "" "" "silent"
run_prompt 54 "the ai captions are too generic make them sound more like me" "NO" "" "" "silent"
run_prompt 55 "add a setting where i describe my writing style so the ai uses it" "NO" "" "" "silent"
run_prompt 56 "add stripe so i can charge for the premium version later" "NO" "" "" "silent"
run_prompt 57 "add a way to track how many ai captions i used this month" "NO" "" "" "silent"
run_prompt 58 "limit free users to 50 captions per month" "NO" "" "" "silent"
run_prompt 59 "add a pricing page with free and premium plans" "NO" "" "" "silent"
run_prompt 60 "premium gets unlimited captions and all platforms" "NO" "" "" "silent"
run_prompt 61 "the trend score is showing wrong numbers fix it" "NO" "" "" "silent"
run_prompt 62 "add a way to filter trends by platform" "NO" "" "" "silent"
run_prompt 63 "add a way to filter trends by category like tech sports fashion" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 64 "add a way to set trend alert threshold so i dont get too many alerts" "NO" "" "" "silent (post-cooldown)"
run_prompt 65 "the email alerts are going to spam fix it" "NO" "" "" "silent"
run_prompt 66 "add push notifications instead of email" "NO" "" "" "silent"
run_prompt 67 "the calendar drag and drop is broken on mobile fix it" "NO" "" "" "silent"
run_prompt 68 "add a way to see post preview before publishing" "NO" "" "" "silent"
run_prompt 69 "the preview should look like an actual tweet or instagram post" "NO" "" "" "silent"
run_prompt 70 "add a way to create twitter threads" "NO" "" "" "silent"
run_prompt 71 "each tweet in the thread should stay under 280 characters" "NO" "" "" "silent"
run_prompt 72 "add a way for users to sign up and create their own account" "YES" "absence:security_check" "2" "absence:security_check"
run_prompt 73 "each user should only see their own posts and trends" "NO" "" "" "silent (post-cooldown)"
run_prompt 74 "add a forgot password page" "NO" "" "" "silent"
run_prompt 75 "add a profile page where users can change their name and photo" "NO" "" "" "silent"
run_prompt 76 "the app is slow when loading many posts fix it" "NO" "" "" "silent"
run_prompt 77 "add a loading spinner" "NO" "" "" "silent"
run_prompt 78 "add a way to export my posts and analytics as csv" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 79 "add a landing page that explains what trendpulse does" "NO" "" "" "silent (post-cooldown)"
run_prompt 80 "the landing page should have a signup button and pricing" "NO" "" "" "silent"
run_prompt 81 "add testimonials to the landing page" "NO" "" "" "silent"
run_prompt 82 "make the landing page look modern with nice animations" "NO" "" "" "silent"
run_prompt 83 "add google analytics to track visitors" "NO" "" "" "silent"
run_prompt 84 "i want to launch it this week" "NO" "" "" "silent"
run_prompt 85 "how do i put it online so people can use it" "YES" "stage_transition" "1" "stage_transition (release)"
run_prompt 86 "its live and i shared it on my instagram story" "NO" "" "" "silent (post-cooldown)"
run_prompt 87 "20 people signed up but 5 say they cant connect their twitter" "NO" "" "" "silent"
run_prompt 88 "the twitter oauth is giving an error fix it" "NO" "" "" "silent"
run_prompt 89 "someone says the trend dashboard is empty for them" "NO" "" "" "silent"
run_prompt 90 "the trend polling is not running for new users fix it" "NO" "" "" "silent"
run_prompt 91 "a user says the ai captions are in english but they want spanish" "NO" "" "" "silent"
run_prompt 92 "add language selection for ai captions" "NO" "" "" "silent"
run_prompt 93 "add support for spanish french and portuguese captions" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 94 "the scheduled post published at the wrong time" "NO" "" "" "silent (post-cooldown)"
run_prompt 95 "i think its a timezone problem fix it" "NO" "" "" "silent"
run_prompt 96 "add timezone setting for each user" "NO" "" "" "silent"
run_prompt 97 "a user paid for premium but the captions are still limited" "NO" "" "" "silent"
run_prompt 98 "the stripe webhook is not updating the subscription status fix it" "NO" "" "" "silent"
run_prompt 99 "someone says the instagram posting shows an error" "NO" "" "" "silent"
run_prompt 100 "instagram needs a two step upload process fix the posting" "NO" "" "" "silent"
run_prompt 101 "the analytics chart is not showing data for new users" "NO" "" "" "silent"
run_prompt 102 "add a way to see analytics for each individual post" "NO" "" "" "silent"
run_prompt 103 "show impressions clicks and shares for each post" "NO" "" "" "silent"
run_prompt 104 "the competitor tracking is showing wrong data for some accounts" "NO" "" "" "silent"
run_prompt 105 "a user says they connected the wrong twitter account how do they disconnect" "NO" "" "" "silent"
run_prompt 106 "add a disconnect button for each platform" "NO" "" "" "silent"
run_prompt 107 "add a way to connect multiple accounts for the same platform" "NO" "" "" "silent"
run_prompt 108 "add tiktok video posting support" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 109 "tiktok needs video only no image posts" "NO" "" "" "silent (post-cooldown)"
run_prompt 110 "the video upload is too slow" "NO" "" "" "silent"
run_prompt 111 "add a progress bar for video uploads" "NO" "" "" "silent"
run_prompt 112 "a user says the weekly email has wrong numbers" "NO" "" "" "silent"
run_prompt 113 "the weekly summary is counting posts from other users fix it" "NO" "" "" "silent"
run_prompt 114 "add a way to see all users who signed up" "NO" "" "" "silent"
run_prompt 115 "add an admin dashboard for me" "NO" "" "" "silent"
run_prompt 116 "show total users total posts and revenue on the admin dashboard" "NO" "" "" "silent"
run_prompt 117 "the free plan users are creating too many accounts to get more captions" "NO" "" "" "silent"
run_prompt 118 "limit one account per email" "NO" "" "" "silent"
run_prompt 119 "add email verification for new signups" "NO" "" "" "silent"
run_prompt 120 "the trend alerts are firing too many times for the same topic" "NO" "" "" "silent"
run_prompt 121 "add a cooldown so the same trend only alerts once per day" "NO" "" "" "silent"
run_prompt 122 "add a way to dismiss a trend alert" "NO" "" "" "silent"
run_prompt 123 "a user says they can see another users draft posts" "YES" "absence:security_check" "2" "absence:security_check"
run_prompt 124 "fix the data isolation so each user only sees their own stuff" "NO" "" "" "silent (post-cooldown)"
run_prompt 125 "add a way for users to delete their account" "NO" "" "" "silent"
run_prompt 126 "the account deletion should remove all their data" "NO" "" "" "silent"
run_prompt 127 "add a contact us page" "NO" "" "" "silent"
run_prompt 128 "add a help page with faq" "NO" "" "" "silent"
run_prompt 129 "the app crashes when uploading large images fix it" "NO" "" "" "silent"
run_prompt 130 "add image size limit and compression" "NO" "" "" "silent"
run_prompt 131 "add instagram reels posting" "NO" "" "" "silent"
run_prompt 132 "add instagram carousel posts with multiple images" "NO" "" "" "silent"
run_prompt 133 "the carousel should let me pick up to 10 images" "NO" "" "" "silent"
run_prompt 134 "add a way to edit images before posting like crop and filter" "NO" "" "" "silent"
run_prompt 135 "add text overlay on images" "NO" "" "" "silent"
run_prompt 136 "add linkedin carousel support too" "NO" "" "" "silent"
run_prompt 137 "the calendar needs a month view not just week" "NO" "" "" "silent"
run_prompt 138 "add a day view for busy days" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 139 "add a bulk upload feature for scheduling many posts at once" "NO" "" "" "silent (post-cooldown)"
run_prompt 140 "the bulk upload should accept a csv file" "NO" "" "" "silent"
run_prompt 141 "show errors for each row if something is wrong in the csv" "NO" "" "" "silent"
run_prompt 142 "add ai content ideas based on trending topics" "NO" "" "" "silent"
run_prompt 143 "show 10 content ideas for the week" "NO" "" "" "silent"
run_prompt 144 "add a way to turn a content idea into a post with one click" "NO" "" "" "silent"
run_prompt 145 "add sentiment analysis for comments on my posts" "NO" "" "" "silent"
run_prompt 146 "show if comments are positive negative or neutral" "NO" "" "" "silent"
run_prompt 147 "add a way to reply to comments from inside the app" "NO" "" "" "silent"
run_prompt 148 "add a/b testing for captions" "NO" "" "" "silent"
run_prompt 149 "post two versions and tell me which one did better after a day" "NO" "" "" "silent"
run_prompt 150 "add a way to recycle old posts that did well" "NO" "" "" "silent"
run_prompt 151 "the ai should rewrite the caption so it doesnt look like a repost" "NO" "" "" "silent"
run_prompt 152 "add a report i can download showing my monthly performance" "NO" "" "" "silent"
run_prompt 153 "make the report look nice with charts and my profile picture" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 154 "add a way to share the report as a link" "NO" "" "" "silent (post-cooldown)"
run_prompt 155 "add a referral program give users 10 free captions for each friend they invite" "NO" "" "" "silent"
run_prompt 156 "show referral stats on the user dashboard" "NO" "" "" "silent"
run_prompt 157 "the stripe is charging wrong amount when users upgrade mid month fix it" "NO" "" "" "silent"
run_prompt 158 "add a free trial of 7 days for premium" "NO" "" "" "silent"
run_prompt 159 "show a countdown for the free trial in the app" "NO" "" "" "silent"
run_prompt 160 "send a reminder email 2 days before trial expires" "NO" "" "" "silent"
run_prompt 161 "add a way to add team members to my account" "NO" "" "" "silent"
run_prompt 162 "team members can create posts but only i can publish" "NO" "" "" "silent"
run_prompt 163 "show who created each post on the calendar" "NO" "" "" "silent"
run_prompt 164 "add slack notifications for trend alerts" "NO" "" "" "silent"
run_prompt 165 "the slack integration should also notify when a post is published" "NO" "" "" "silent"
run_prompt 166 "add a way to connect google analytics to track link clicks" "NO" "" "" "silent"
run_prompt 167 "auto add utm tags to links in posts" "NO" "" "" "silent"
run_prompt 168 "add link shortening for post links" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 169 "show click count for each shortened link" "NO" "" "" "silent (post-cooldown)"
run_prompt 170 "add a way to pin important trends to the top of the dashboard" "NO" "" "" "silent"
run_prompt 171 "add a search bar to find old posts" "NO" "" "" "silent"
run_prompt 172 "the search should work by keyword platform and date" "NO" "" "" "silent"
run_prompt 173 "i think v1.1 is ready lets update the live app" "NO" "" "" "silent"
run_prompt 174 "add a way for team members to have their own login" "YES" "absence:security_check" "2" "absence:security_check"
run_prompt 175 "push all the new features to production" "YES" "stage_transition" "1" "stage_transition (v1.1 release)"
run_prompt 176 "the carousel posting on instagram is showing images in wrong order" "NO" "" "" "silent (post-cooldown)"
run_prompt 177 "fix the image order for instagram carousels" "NO" "" "" "silent"
run_prompt 178 "a team member says they can see billing info they should not see that" "NO" "" "" "silent"
run_prompt 179 "hide billing from team members only show to account owner" "NO" "" "" "silent"
run_prompt 180 "the bulk csv upload is crashing for files with more than 100 rows" "NO" "" "" "silent"
run_prompt 181 "add pagination for large csv imports" "NO" "" "" "silent"
run_prompt 182 "a user wants to post pinterest pins add pinterest support" "NO" "" "" "silent"
run_prompt 183 "add pinterest board selection when creating a pin" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 184 "the pinterest posting needs an image for every pin" "NO" "" "" "silent (post-cooldown)"
run_prompt 185 "add youtube shorts posting" "NO" "" "" "silent"
run_prompt 186 "the video upload limit is too small increase it to 100mb" "NO" "" "" "silent"
run_prompt 187 "the sentiment analysis is wrong for sarcastic comments" "NO" "" "" "silent"
run_prompt 188 "the weekly email looks ugly on mobile" "NO" "" "" "silent"
run_prompt 189 "make the weekly email responsive" "NO" "" "" "silent"
run_prompt 190 "add a way to see which platform brings the most engagement" "NO" "" "" "silent"
run_prompt 191 "show a platform comparison chart" "NO" "" "" "silent"
run_prompt 192 "add a way to schedule instagram stories" "NO" "" "" "silent"
run_prompt 193 "stories should auto-delete after 24 hours" "NO" "" "" "silent"
run_prompt 194 "add a content calendar printable version" "NO" "" "" "silent"
run_prompt 195 "the trend detection is missing youtube trends add them" "NO" "" "" "silent"
run_prompt 196 "show youtube trending videos related to my keywords" "NO" "" "" "silent"
run_prompt 197 "add a way to see what time my followers are most active per platform" "NO" "" "" "silent"
run_prompt 198 "show the best posting times as a heatmap" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 199 "the ai is using too many emojis in captions" "NO" "" "" "silent (post-cooldown)"
run_prompt 200 "add an emoji setting to control how many emojis the ai uses" "NO" "" "" "silent"
run_prompt 201 "add a way to save hashtag groups like fitness hashtags or food hashtags" "NO" "" "" "silent"
run_prompt 202 "auto suggest the right hashtag group based on post content" "NO" "" "" "silent"
run_prompt 203 "add a way to ban certain hashtags that dont work for my brand" "NO" "" "" "silent"
run_prompt 204 "the analytics are not fetching for some old posts fix it" "NO" "" "" "silent"
run_prompt 205 "the tiktok connection keeps expiring fix the token refresh" "NO" "" "" "silent"
run_prompt 206 "add a notification when a platform connection expires" "NO" "" "" "silent"
run_prompt 207 "add auto reconnect for expired tokens" "NO" "" "" "silent"
run_prompt 208 "add a way to store credit card info for faster checkout" "YES" "absence:security_check" "2" "absence:security_check"
run_prompt 209 "show last 4 digits of saved card only" "NO" "" "" "silent (post-cooldown)"
run_prompt 210 "the competitor tracking is showing private accounts as public fix it" "NO" "" "" "silent"
run_prompt 211 "add a way to skip private competitor accounts" "NO" "" "" "silent"
run_prompt 212 "add engagement rate calculation for each post" "NO" "" "" "silent"
run_prompt 213 "add a benchmark showing if my engagement is above or below average" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 214 "the benchmark should compare me to similar accounts in my niche" "NO" "" "" "silent (post-cooldown)"
run_prompt 215 "add a way to tag posts by campaign" "NO" "" "" "silent"
run_prompt 216 "show campaign performance analytics" "NO" "" "" "silent"
run_prompt 217 "the app is crashing on iphone safari fix it" "NO" "" "" "silent"
run_prompt 218 "v1.2 is ready lets deploy" "NO" "" "" "silent"
run_prompt 219 "push the updates to production" "YES" "stage_transition" "1" "stage_transition (v1.2 release)"
run_prompt 220 "a user says their scheduled posts all failed after the update" "NO" "" "" "silent (post-cooldown)"
run_prompt 221 "fix the scheduled posts that failed they all have wrong api tokens" "NO" "" "" "silent"
run_prompt 222 "the update broke the token storage fix it" "NO" "" "" "silent"
run_prompt 223 "requeue all the failed posts from yesterday" "NO" "" "" "silent"
run_prompt 224 "add a way to manually retry failed posts" "NO" "" "" "silent"
run_prompt 225 "show failed posts in red on the calendar" "NO" "" "" "silent"
run_prompt 226 "add an ai strategy advisor that tells me what to post more of" "NO" "" "" "silent"
run_prompt 227 "the strategy should look at what performed best last month" "NO" "" "" "silent"
run_prompt 228 "show the strategy as a weekly email with suggestions" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 229 "add auto scheduling that picks the best time for each post" "NO" "" "" "silent (post-cooldown)"
run_prompt 230 "the auto schedule should use my analytics data" "NO" "" "" "silent"
run_prompt 231 "add a way to approve or change the suggested time" "NO" "" "" "silent"
run_prompt 232 "add content recycling suggestions for old posts" "NO" "" "" "silent"
run_prompt 233 "only suggest recycling posts older than 30 days" "NO" "" "" "silent"
run_prompt 234 "the ai should rewrite the recycled caption" "NO" "" "" "silent"
run_prompt 235 "add a way to create post series like tip of the day" "NO" "" "" "silent"
run_prompt 236 "the series should auto number each post" "NO" "" "" "silent"
run_prompt 237 "add a way to see which days i have no posts scheduled" "NO" "" "" "silent"
run_prompt 238 "highlight empty days on the calendar" "NO" "" "" "silent"
run_prompt 239 "add a way to quickly fill empty days with ai content" "NO" "" "" "silent"
run_prompt 240 "the trend prediction should tell me whats going to trend tomorrow" "NO" "" "" "silent"
run_prompt 241 "show predicted trends with a confidence score" "NO" "" "" "silent"
run_prompt 242 "add a way to create a post directly from a predicted trend" "NO" "" "" "silent"
run_prompt 243 "add audience insights showing what type of followers i have" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 244 "show audience demographics like age and location" "NO" "" "" "silent (post-cooldown)"
run_prompt 245 "add a way to see which content type works for which audience segment" "NO" "" "" "silent"
run_prompt 246 "the premium plan is not making enough money add a pro plan in between" "NO" "" "" "silent"
run_prompt 247 "pro plan gets 200 captions and 3 team members" "NO" "" "" "silent"
run_prompt 248 "agency plan gets unlimited everything" "NO" "" "" "silent"
run_prompt 249 "update the pricing page with all three plans" "NO" "" "" "silent"
run_prompt 250 "the stripe proration is wrong when upgrading from pro to agency" "NO" "" "" "silent"
run_prompt 251 "add annual billing with 2 months free discount" "NO" "" "" "silent"
run_prompt 252 "add a coupon code system for discounts" "NO" "" "" "silent"
run_prompt 253 "add an affiliate program 20 percent commission" "NO" "" "" "silent"
run_prompt 254 "show affiliate stats on the user dashboard" "NO" "" "" "silent"
run_prompt 255 "the analytics dashboard is too slow with lots of data" "NO" "" "" "silent"
run_prompt 256 "add caching for the analytics page" "NO" "" "" "silent"
run_prompt 257 "add a way to export analytics as pdf report" "NO" "" "" "silent"
run_prompt 258 "the pdf report should have nice charts and branding" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 259 "add white label option for agencies to use their own branding" "NO" "" "" "silent (post-cooldown)"
run_prompt 260 "white label should change logo colors and domain" "NO" "" "" "silent"
run_prompt 261 "add custom domain support" "NO" "" "" "silent"
run_prompt 262 "the ssl setup for custom domains is confusing make it easier" "NO" "" "" "silent"
run_prompt 263 "add a way to see all users sorted by last active date" "NO" "" "" "silent"
run_prompt 264 "send reactivation emails to users inactive for 30 days" "NO" "" "" "silent"
run_prompt 265 "lets deploy v1.3 with all these features" "NO" "" "" "silent"
run_prompt 266 "push everything to production" "YES" "stage_transition" "1" "stage_transition (v1.3 release)"
run_prompt 267 "the auto scheduling is picking midnight as best time thats wrong" "NO" "" "" "silent (post-cooldown)"
run_prompt 268 "fix the timezone in auto scheduling" "NO" "" "" "silent"
run_prompt 269 "a user says the content recycling suggested a post from yesterday not 30 days" "NO" "" "" "silent"
run_prompt 270 "fix the 30 day filter for recycling" "NO" "" "" "silent"
run_prompt 271 "the white label custom domain is not working for one agency" "NO" "" "" "silent"
run_prompt 272 "their dns is not pointing correctly add a dns check tool" "NO" "" "" "silent"
run_prompt 273 "add a way to verify dns is correct before enabling custom domain" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 274 "the pdf report takes too long to generate for users with 500 posts" "NO" "" "" "silent (post-cooldown)"
run_prompt 275 "speed up the report by only including top 50 posts" "NO" "" "" "silent"
run_prompt 276 "the trend prediction is always wrong it never predicts correctly" "NO" "" "" "silent"
run_prompt 277 "improve the prediction by using more historical data" "NO" "" "" "silent"
run_prompt 278 "the affiliate tracking is not recording clicks" "NO" "" "" "silent"
run_prompt 279 "fix the affiliate link tracking" "NO" "" "" "silent"
run_prompt 280 "a user says the coupon code is not applying the discount" "NO" "" "" "silent"
run_prompt 281 "fix the coupon code validation" "NO" "" "" "silent"
run_prompt 282 "the calendar is showing posts from deleted team members" "NO" "" "" "silent"
run_prompt 283 "fix it to hide posts from removed team members or reassign them" "NO" "" "" "silent"
run_prompt 284 "someone is abusing the coupon system creating unlimited discount codes" "YES" "absence:security_check" "2" "absence:security_check"
run_prompt 285 "add a limit of one coupon per account" "NO" "" "" "silent (post-cooldown)"
run_prompt 286 "add usage limits for each coupon code" "NO" "" "" "silent"
run_prompt 287 "the annual billing is not calculating correctly" "NO" "" "" "silent"
run_prompt 288 "fix the annual billing to charge for 10 months not 12" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 289 "a user on the agency plan says they can see other agency users data" "NO" "" "" "silent (post-cooldown)"
run_prompt 290 "fix the data isolation for agency accounts" "NO" "" "" "silent"
run_prompt 291 "the app is crashing when someone has 1000 scheduled posts" "NO" "" "" "silent"
run_prompt 292 "add pagination to the calendar and post list" "NO" "" "" "silent"
run_prompt 293 "the ai caption api is returning errors more often lately" "NO" "" "" "silent"
run_prompt 294 "add a fallback when openai api is down show a message instead of crashing" "NO" "" "" "silent"
run_prompt 295 "the instagram story scheduling doesnt work for business accounts" "NO" "" "" "silent"
run_prompt 296 "fix instagram story api for business accounts" "NO" "" "" "silent"
run_prompt 297 "the engagement tracking is missing data for some platforms" "NO" "" "" "silent"
run_prompt 298 "add retry for analytics fetching when platform api fails" "NO" "" "" "silent"
run_prompt 299 "some users want to integrate with their crm" "NO" "" "" "silent"
run_prompt 300 "add a public api so other tools can connect to trendpulse" "NO" "" "" "silent"
run_prompt 301 "add api key management for users" "NO" "" "" "silent"
run_prompt 302 "the api should let users create posts and get analytics" "NO" "" "" "silent"
run_prompt 303 "add rate limiting to the api 60 requests per minute" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 304 "add api documentation page" "NO" "" "" "silent (post-cooldown)"
run_prompt 305 "add ai video generation from text prompts" "NO" "" "" "silent"
run_prompt 306 "the ai video should create short clips for tiktok and reels" "NO" "" "" "silent"
run_prompt 307 "video generation takes too long show a progress bar" "NO" "" "" "silent"
run_prompt 308 "add notification when video is ready" "NO" "" "" "silent"
run_prompt 309 "add a social inbox to see all comments and messages in one place" "NO" "" "" "silent"
run_prompt 310 "the inbox should show which platform each message is from" "NO" "" "" "silent"
run_prompt 311 "add a way to reply to messages from the inbox" "NO" "" "" "silent"
run_prompt 312 "add ai suggested replies for common questions" "NO" "" "" "silent"
run_prompt 313 "add a crisis mode that pauses all scheduled posts" "NO" "" "" "silent"
run_prompt 314 "crisis mode should alert the whole team" "NO" "" "" "silent"
run_prompt 315 "add a way to resume posts after crisis is over" "NO" "" "" "silent"
run_prompt 316 "add an influencer database to find people to collaborate with" "NO" "" "" "silent"
run_prompt 317 "show influencer follower count and engagement rate" "NO" "" "" "silent"
run_prompt 318 "add a way to reach out to influencers from inside the app" "YES" "absence:test_creation" "2" "absence:test_creation"
run_prompt 319 "add gdpr data export so users can download their data" "NO" "" "" "silent (post-cooldown)"
run_prompt 320 "add account deletion with 30 day grace period" "NO" "" "" "silent"
run_prompt 321 "add a marketplace where agencies can list their services" "NO" "" "" "silent"
run_prompt 322 "the marketplace should have reviews and ratings" "NO" "" "" "silent"
run_prompt 323 "add a way to message agencies from the marketplace" "NO" "" "" "silent"
run_prompt 324 "add internationalization for the whole app" "NO" "" "" "silent"
run_prompt 325 "support english spanish french portuguese japanese" "NO" "" "" "silent"
run_prompt 326 "the ai captions should generate in the users language" "NO" "" "" "silent"
run_prompt 327 "add a mobile app or at least make the website an installable pwa" "NO" "" "" "silent"
run_prompt 328 "the pwa should work offline for viewing scheduled posts" "NO" "" "" "silent"
run_prompt 329 "add a changelog page showing new features" "NO" "" "" "silent"
run_prompt 330 "show unread feature updates with a badge" "NO" "" "" "silent"
run_prompt 331 "i want to launch v2.0 with all these features" "NO" "" "" "silent"
run_prompt 332 "add a way for marketplace agencies to accept payments through trendpulse" "YES" "absence:security_check" "2" "absence:security_check"
run_prompt 333 "take a 5 percent platform fee from marketplace transactions" "NO" "" "" "silent (post-cooldown)"
run_prompt 334 "deploy v2.0 to production" "YES" "stage_transition" "1" "stage_transition (v2.0 release)"
run_prompt 335 "v2.0 is live 50 new users signed up on the first day" "NO" "" "" "silent (post-cooldown)"
run_prompt 336 "the marketplace payment is not processing for some agencies" "NO" "" "" "silent"
run_prompt 337 "fix the stripe connect setup for marketplace sellers" "NO" "" "" "silent"
run_prompt 338 "the ai video generation is producing blurry videos fix quality" "NO" "" "" "silent"
run_prompt 339 "a user says the social inbox shows messages from disconnected accounts" "NO" "" "" "silent"
run_prompt 340 "trendpulse has 500 users now and growing i need to add a support chat" "NO" "" "" "silent"

windsurf_test_finish
